name: TLA+ Model Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  model_check:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Download TLC tools
    - name: Download TLC tools
      run: wget https://github.com/tlaplus/tlaplus/releases/latest/download/tla2tools.jar

    # Find all .cfg files and run TLC for each
    - name: Find and run all configuration files
      run: |
        configs=$(ls ./configs/*.cfg)
        for config in $configs; do
          echo "::group::Running TLC on $config"
          java -cp tla2tools.jar tlc2.TLC -config "$config" p2p.tla
          if [ $? -ne 0 ]; then
            echo "::error file=$config::TLC failed on $config"
            exit 1
          fi
          echo "::endgroup::"
        done
