name: TLA+ Model Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  model_check:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    # Run the TLA+ Model Checker (TLC)
    - name: Run TLC model checker
      run: |
        wget https://github.com/tlaplus/tlaplus/releases/latest/download/tla2tools.jar
        java -cp tla2tools.jar tlc2.TLC -deadlock -config p2p.cfg p2p.tla
